---
apiVersion: v1
kind: ConfigMap
metadata:
  name: caddy-cm
data:
  index.html: |
    hello
---
apiVersion: v1
kind: Pod
metadata:
  name: caddy
spec:
  containers:
    - name: caddy
      image: caddy
      volumeMounts:
        - name: index
          mountPath: /usr/share/caddy/
  volumes:
    - name: index
      configMap:
        name: caddy-cm
