---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod1
spec:
  nodeName: pl01-c2-10-1-16-10
  containers:
    - name: c1
      image: quay.io/centos/centos:stream8
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      command:
        - sleep
        - infinity
---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: pod2
spec:
  nodeName: pl01-c2-10-1-16-231
  containers:
    - name: c1
      image: quay.io/centos/centos:stream8
      resources:
        requests:
          memory: "64Mi"
          cpu: "250m"
        limits:
          memory: "128Mi"
          cpu: "500m"
      command:
        - sleep
        - infinity
