---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: ealen/echo-server:latest
          env:
            - { name: PORT, value: "8080" }
          readinessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 10
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: echoserver
