---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: googlecontainer/echoserver:1.5
          readnessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 10
            periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: echoserver

---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: echoserver
spec:
  host: echoserver.local
  to:
    kind: Service
    name: echoserver
  port:
    targetPort: http
