---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gogs

spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: gogs
    spec:
      containers:
        - name: gogs
          image: gogs/gogs
---
apiVersion: v1
kind: Service
metadata:
  name: svc-for-gogs
spec:
  ports:
    - name: ssh
      port: 22
      targetPort: 22
    - name: http
      port: 3000
      targetPort: 3000
  selector:
    name: gogs
  type: NodePort
