---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: httpbin
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      containers:
        - name: httpbin
          image: jeffrey4l/httpbin
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: httpbin
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: httpbin
spec:
  host: httpbin.local
  to:
    kind: Service
    name: httpbin
  port:
    targetPort: http
