---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: httpbin
spec:
  template:
    metadata:
      labels:
        app: httpbin
    spec:
      replicas: 1
      containers:
        - name: httpbin
          image: kennethreitz/httpbin
          ports:
            - containerPort: 80
              name: http
              protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: httpbin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
  selector:
    app: httpbin
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: httpbin
spec:
  host: httpbin.local
  to:
    kind: Service
    name: httpbin
  port:
    targetPort: http
