---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0001 
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /data/asb_etcd
    server: 10.3.0.20
  persistentVolumeReclaimPolicy: Recycle 

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv0002
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /data2
    server: 10.2.0.60
  persistentVolumeReclaimPolicy: Recycle 
