---
apiVersion: v1
kind: ConfigMap
metadata:
  name: conf
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    alerting:
      alertmanagers:
      - static_configs:
        - targets:
    rule_files: []
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
        - targets: ['localhost:9090']
      - job_name: 'pods'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - test
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: pod_name
          - source_labels:
              - __meta_kubernetes_pod_container_name
            action: keep
            regex: node-export
      - job_name: 'nginx'
        kubernetes_sd_configs:
          - role: pod
            namespaces:
              names:
                - test
        metrics_path: "/status/format/prometheus"
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_pod_label_(.+)
          - source_labels:
              - __meta_kubernetes_pod_name
            action: replace
            target_label: pod_name
          - source_labels:
              - __meta_kubernetes_pod_label_deploymentconfig
            action: keep
            regex: php
          - source_labels: [ __address__ ]
            action: replace
            regexp: ([^:]+)
            replacement: $1:8081
            target_label: __address__

---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: node-exporter
spec:
  selector:
    app: node-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      volumes:
      containers:
        - name: node-export
          image: prom/node-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9100
---
apiVersion: v1
kind: DeploymentConfig
metadata:
  name: prometheus
spec:
  selector:
    app: prometheus
  replicas: 1
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      volumes:
        - name: conf
          configMap:
            name: conf
        - name: data
          # emptyDir: {}
          hostPath:
            path: /data/prometheus
      containers:
        - name: prometheus
          image: prom/prometheus
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9090
          volumeMounts:
            - name: data
              mountPath: /prometheus
            - name: conf
              mountPath: /etc/prometheus/prometheus.yml
              subPath: prometheus.yml
        - name: node-export
          image: prom/node-exporter
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 9100
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
spec:
  ports:
    - name: http
      port: 9090
      targetPort: 9090
  selector:
    app: prometheus
  thttp://10.131.0.130:9100/metricsype: NodePort
