---
apiVersion: v1
kind: Template
metadata:
  name: simple-pod-tpl
parameters:
  - name: NAME
    required: true
    value: echoserver
  - name: IMAGE
    required: true
    value: centos:7
objects:
  - kind: Pod
    apiVersion: v1
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
    spec:
      containers:
        - name: echoserver
          image: ${IMAGE}
          command:
            - sleep
            - infinity
