---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  containers:
  - name: echoserver
    image: googlecontainer/echoserver:1.5
    ports:
    - containerPort: 8080
