---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: echoserver
spec:
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - name: echoserver
          image: googlecontainer/echoserver:1.5

---
apiVersion: v1
kind: Service
metadata:
  name: http-for-echoserver
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: echoserver
  type: NodePort
