---
apiVersion: v1
kind: Pod
metadata:
  name: echoserver
  labels:
    app: echoserver
spec:
  containers:
    - name: echoserver
      image: ealen/echo-server:latest
      ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: echoserver
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: echoserver
  type: NodePort
