---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv001
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    path: /srv/share-1
    server: 10.3.0.111
  persistentVolumeReclaimPolicy: Recycle
