---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-default
  annotations:
    storageclass.beta.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/rbd
parameters:
  monitors: 10.3.0.21:6789,10.3.0.23:6789,10.3.0.24:6789
  adminId: admin
  adminSecretName: ceph-secret
  adminSecretNamespace: kube-system
  pool: kube
  userId: kube
  userSecretName: ceph-user-secret
