---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: etcd-vol2
spec:
  capacity:
    storage: 5Gi 
  accessModes:
  - ReadWriteOnce 
  nfs: 
    path: /exports/etcd
    server: 172.21.21.17
  persistentVolumeReclaimPolicy: Recycle 
