---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: echoserver
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: echoserver
    spec:
{% if run_as_root %}
      serviceAccountName: echoserver
{% endif %}
      containers:
        - name: echoserver
          image: "{{ image }}"
          readnessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 20
            periodSeconds: 5
          livenessProbe:
            httpGet:
              port: 8080
              path: /
            initialDelaySeconds: 10
            periodSeconds: 3
