---
apiVersion: v1
kind: Template
metadata:
  name: centos7-tpl
parameters:
  - name: NAME
    required: true
    value: centos7
objects:
  - apiVersion: v1
    kind: Pod
    metadata:
      name: ${NAME}
      labels:
        app: ${NAME}
        created-by: centos7-tpl
    spec:
      containers:
        - name: centos
          image: centos:7
          command:
            - sleep
            - infinity
